### ISSUE TITLE
"Last 10 Blocked IP Addresses"  of  Dashboard  Page/Screen.

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/limit-attempts-master#13]
Hi Shifi,

Here are the tasks for you for the "Last 10 Blocked IP Addresses"  of  Dashboard  Page/Screen.

• Create a layout same as "Manage IP Address" Page of Log Sidebar.
• 10 Recent Logs should show on those fields from the database.
• Bulk Delete and single Delete also should work properly.

**Comment by tech-prodigy5** [comment]
Issue Id: #13 

# Changed Files: 

1.lib\install-script.php
2.includes\footer.php
3.include\queries.php
4.lib\action-library.php
5.views\Dashboard\Last 10 Blocked IP Addresses\Last 10 Blocked IP Addresses.php

# Issues Fixed:

1.Bulk Delete and single Delete worked properly.
2.Toster notification shown after click on save setting.
3.Loader Works properly and refreshes the page after the update.
4.All the feilds are sanitized properly.
5.All the data will be shown on the from the database.

Note: Reported issues are fixed. So this issue is marked as closed.

Changed by:
Shiffi Mehta
